name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm svelte-check
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm prettier-check
      - run: pnpm lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
          fetch-tags: true
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: pnpm
      - run: pnpm i --frozen-lockfile
      - run: pnpm build
        name: Build library
        env:
          ILLUMINATRIX_LIB: "1"
          ILLUMINATRIX_OUT_DIR: ./dist-lib/
      - run: pnpm build
        name: Build standalone
        env:
          ILLUMINATRIX_OUT_DIR: ./dist-standalone/
      - name: Git describe
        id: git-describe
        run: echo tag=$(git describe --always) >> $GITHUB_OUTPUT
      - name: Upload library build
        uses: actions/upload-artifact@v4
        with:
          path: dist-lib
          name: dist-lib-${{ steps.git-describe.outputs.tag }}
